### ISSUE TITLE
Can no longer access my Admin pages on Wordpress.org 

### ISSUE THREAD

**Issue by ludojoosen** [ArthurGareginyan/all-meta-tags#1]
When I try to access the Admin pages of my Wordpress site I get the following information

Warning: Constants may only evaluate to scalar values in /home/ludojoosen/public_html/wp-content/plugins/all-meta-tags/all-meta-tags.php on line 69

Warning: Cannot modify header information - headers already sent by (output started at /home/ludojoosen/public_html/wp-content/plugins/all-meta-tags/all-meta-tags.php:69) in /home/ludojoosen/public_html/wp-includes/pluggable.php on line 904
I love Antwerp

And a little further on there is

ERROR: Cookies are blocked due to unexpected output. For help, please see this documentation or try the support forums.

This only happened today, up till now things have been going fine.

What can I do?

Ludo

**Comment by ArthurGareginyan** [comment]
Thank you for reaching out. I'm sorry that you had this problem.

Fortunately I have a solution and recently released an update that fixed this issue. I understand that you’re not able to access your WordPress dashboard, so a manual removal via FTP is needed in order to get back in.

You can remove the plugin via FTP. This would require access to your control panel via your web hosting solution.

Once logged into your FTP, you can find the folder under `/public-html/domain-name.com/wp-content/plugins/all-meta-tags/`.
Delete the whole folder of `/all-meta-tags/` and you should have access to your WordPress dashboard again.
Once removed you should be able to get back into your WordPress back end and reinstall the new version which is completely compatible.

If you’re having issues with this, most hosting support can do this on their end for you.

I apologize again about this error, please let me know if you have any other questions or feedback.
